version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
     LOG_LEVEL: TRACE # Log SQL queries
      PRISMA_CONFIG: |
        port: 4466
        LOG_LEVEL: TRACE # Log SQL queries
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-84-100.eu-west-1.compute.amazonaws.com
            database: d806gdt6j9cfmu
            schema: public
            user: awvzbtorxbdoam
            password: 61667bbe1ba12092e64ff9c311a1332e8bb0f2c4aa63c251a7cfcab0e8b0ca49
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true